name: Auto Build, Publish, Releasing

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'release type'
        required: true
        type: choice
        default: 'beta'
        options:
          - 'release'
          - 'beta'
          - 'alpha'
      publishMaven:
        description: 'whether publish to the maven'
        required: true
        type: boolean
        default: true
      publishCurseForgeAndModrinth:
        description: 'whether publish to the curseforge and modrinth'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - if: ${{ inputs.publishMaven }}
        name: Publish to Maven
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish

      - if: ${{ inputs.publishCurseForgeAndModrinth }}
        name: Get Version
        id: var
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | grep shadow.jar -v | grep all.jar -v | awk -F 'multiblocked2-|.jar' '{print $2}')
          echo forge_version=$MESSAGE >> $GITHUB_OUTPUT

      - if: ${{ inputs.publishCurseForgeAndModrinth }}
        name: mc-publish-forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: R2gjKEpa
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 1104057
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc|dev-shadow|all)).jar
            build/libs/*-@(dev|sources|javadoc|dev-shadow|all).jar

          name: Multiblocked2 ${{ steps.var.outputs.forge_version }}-forge
          version: mc${{ steps.var.outputs.forge_version }}-forge
          version-type: ${{ inputs.releaseType }}
          changelog-file: CHANGELOG.*

          loaders: |
            forge
          game-versions: |
            ${{ github.ref_name }}
          game-version-filter: none
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail